## Simple neural network
based on <a href="https://towardsdatascience.com/how-to-build-your-own-neural-network-from-scratch-in-python-68998a08e4f6">article</a> published by James Loy


In [1]:
# required imports
import numpy as np

<img src="neural_net.png">

In [2]:
# definition of neural network with input layer, one hidden layer and an output layer

# neuron activation function is sigmoid function defined as:

def sigmoid(x, derivative=False):
    return x*(1-x) if derivative else 1/(1+np.exp(-x))

class NeuralNetwork:
    
    def __init__(self, x, y):
        self.input = x
        # weights from input layer to hidden layer with 4 neurons
        self.weights1 = np.random.rand(self.input.shape[1], 4)
        # weights from hidden layer to output layer with 1 neuron
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np.zeros(y.shape)
        
    # feed forward to obtain network output
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        
    # backpropagation to update the weights
    def backprop(self):
        # application of chain rule to find derivative of loss function
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output)*sigmoid(self.output, derivative=True)))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y - self.output)*sigmoid(self.output, derivative=True), 
                                                 self.weights2.T)*sigmoid(self.layer1, derivative=True))
        
        # updating the weights with slope of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

In [3]:
# example of weights from input with 3 neurons to hidden layer with 4 neurons
# first row contains the weights from first input neuron to all the neurons in the hidden layer and so on
np.random.rand(3,4)

array([[0.40123225, 0.12045488, 0.62217359, 0.69536746],
       [0.96777618, 0.58043368, 0.75528643, 0.67166788],
       [0.98515104, 0.59189078, 0.00415841, 0.99167859]])

In [4]:
# example of weigths from hiddne layer with 4 neurons to one output neuron
np.random.rand(4,1)

array([[0.66476024],
       [0.16856527],
       [0.35035467],
       [0.0366572 ]])

In [5]:
# definition of inputs
X = np.array([[0, 0, 1],
            [0, 1, 1],
            [1, 0, 1],
            [1, 1, 1]])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [6]:
# definition of outputs
y = np.array([[0], [1], [1], [0]])
y

array([[0],
       [1],
       [1],
       [0]])

In [7]:
# creation of the neural network
net1= NeuralNetwork(X, y)

In [8]:
net1.feedforward()

In [9]:
net1.output

array([[0.67942476],
       [0.70692169],
       [0.701449  ],
       [0.72536373]])

In [10]:
net1.backprop()

In [11]:
net1.output

array([[0.67942476],
       [0.70692169],
       [0.701449  ],
       [0.72536373]])

In [12]:
# training the network with 1500 iterations of feed forward and backpropagation
for i in range(1500):
    net1.feedforward()
    net1.backprop()

# network prediction after training
net1.output

array([[0.01910024],
       [0.98225769],
       [0.97460176],
       [0.02383271]])